/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yangchi' at '8/8/14 11:40 PM' with Gradle 2.0
 *
 * @author yangchi, @date 8/8/14 11:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
